#!/usr/bin/env bash
set -euo pipefail

# ─── Configurable variables ──────────────────────────────────────────────────
REGISTRY=""                          # e.g. "registry.example.com/myorg" (leave empty for no prefix)
IMAGE_BACKEND="wacchat-backend"
IMAGE_FRONTEND="wacchat-frontend"
IMAGE_FILE_SERVICE="wacchat-file-service"
IMAGE_API_GATEWAY="wacchat-api-gateway"
IMAGE_NOTIFICATION_SERVICE="wacchat-notification-service"
IMAGE_CALL_SERVICE="wacchat-call-service"
TAG="latest"
CONTAINER_BACKEND="wacchat-backend"
CONTAINER_FRONTEND="wacchat-frontend"
CONTAINER_FILE_SERVICE="wacchat-file-service"
CONTAINER_API_GATEWAY="wacchat-api-gateway"
CONTAINER_NOTIFICATION_SERVICE="wacchat-notification-service"
CONTAINER_CALL_SERVICE="wacchat-call-service"
PORT_BACKEND=8082
PORT_FRONTEND=4200
PORT_FILE_SERVICE=8083
PORT_API_GATEWAY=8085   # host-side only; container still listens on 8081 internally (Pi-hole owns 8081 on this host)
PORT_NOTIFICATION_SERVICE=8084
PORT_CALL_SERVICE=8086  # host-side only; container listens on 8085 internally (avoids clashing with PORT_API_GATEWAY's host mapping)
COMPOSE_DIR="."
# ─────────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WAC_DIR="$SCRIPT_DIR/wac"
BACKEND_DIR="$SCRIPT_DIR/wac/backend"
FRONTEND_DIR="$SCRIPT_DIR/wac/frontend"
FILE_SERVICE_DIR="$SCRIPT_DIR/wac/file-service"
API_GATEWAY_DIR="$SCRIPT_DIR/wac/api-gateway"
NOTIFICATION_SERVICE_DIR="$SCRIPT_DIR/wac/notification-service"
CALL_SERVICE_DIR="$SCRIPT_DIR/wac/call-service"

# ─── Auto-generate .env with strong passwords if missing ─────────────────────
if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
  echo "[deploy] .env not found — generating strong passwords..."
  cat > "$SCRIPT_DIR/.env" <<EOF
# Auto-generated by deploy.sh on $(date '+%Y-%m-%d %H:%M:%S')
# Keep this file secret — never commit it.

POSTGRES_USER=wacchat
POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)
POSTGRES_DB=wacchat_db

KEYCLOAK_ADMIN_USERNAME=admin
KEYCLOAK_ADMIN_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)

FILE_SERVICE_INTERNAL_API_KEY=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)

RABBITMQ_USER=wacchat
RABBITMQ_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)
RABBITMQ_BACKEND_USER=wacchat-backend
RABBITMQ_BACKEND_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)
RABBITMQ_NOTIFICATION_USER=wacchat-notification
RABBITMQ_NOTIFICATION_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)
RABBITMQ_CALL_USER=wacchat-call
RABBITMQ_CALL_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)

BACKEND_INTERNAL_API_KEY=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)

GRAFANA_ADMIN_USER=admin
GRAFANA_ADMIN_PASSWORD=$(openssl rand -base64 32 | tr -dc 'A-Za-z0-9' | head -c 32)
EOF
  echo "[deploy] .env created at $SCRIPT_DIR/.env — save the Keycloak admin password before proceeding."
fi

# Load .env
set -a; source "$SCRIPT_DIR/.env"; set +a

# Generate Keycloak realm JSON from template
REALM_TEMPLATE="$SCRIPT_DIR/wac/keycloak/realms/wacchat.json.template"
REALM_OUTPUT="$SCRIPT_DIR/wac/keycloak/realms/wacchat.json"
[[ -f "$REALM_TEMPLATE" ]] || err "Realm template not found: $REALM_TEMPLATE"
_pw_orig="${MAIL_PASSWORD:-}"
if [[ ${#_pw_orig} -eq 16 ]]; then
  MAIL_PASSWORD="${_pw_orig:0:4} ${_pw_orig:4:4} ${_pw_orig:8:4} ${_pw_orig:12:4}"
fi
: "${APP_BASE_URL:=https://wacchat.win}"
envsubst '${MAIL_USERNAME} ${MAIL_PASSWORD} ${MAIL_FROM} ${APP_BASE_URL}' < "$REALM_TEMPLATE" > "$REALM_OUTPUT"
MAIL_PASSWORD="$_pw_orig"

# Generate RabbitMQ definitions (per-consumer credentials) from template.
# Falls back to the shared RABBITMQ_USER/PASSWORD if the per-service vars aren't set in
# .env, so existing deployments keep working with a single admin account unless you opt
# into separated credentials.
: "${RABBITMQ_USER:=wacchat}"
: "${RABBITMQ_PASSWORD:=wacchat}"
: "${RABBITMQ_BACKEND_USER:=$RABBITMQ_USER}"
: "${RABBITMQ_BACKEND_PASSWORD:=$RABBITMQ_PASSWORD}"
: "${RABBITMQ_NOTIFICATION_USER:=$RABBITMQ_USER}"
: "${RABBITMQ_NOTIFICATION_PASSWORD:=$RABBITMQ_PASSWORD}"
: "${RABBITMQ_CALL_USER:=$RABBITMQ_USER}"
: "${RABBITMQ_CALL_PASSWORD:=$RABBITMQ_PASSWORD}"
RABBITMQ_DEFS_TEMPLATE="$SCRIPT_DIR/wac/rabbitmq/definitions.json.template"
RABBITMQ_DEFS_OUTPUT="$SCRIPT_DIR/wac/rabbitmq/definitions.json"
envsubst '${RABBITMQ_USER} ${RABBITMQ_PASSWORD} ${RABBITMQ_BACKEND_USER} ${RABBITMQ_BACKEND_PASSWORD} ${RABBITMQ_NOTIFICATION_USER} ${RABBITMQ_NOTIFICATION_PASSWORD} ${RABBITMQ_CALL_USER} ${RABBITMQ_CALL_PASSWORD}' \
  < "$RABBITMQ_DEFS_TEMPLATE" > "$RABBITMQ_DEFS_OUTPUT"

PUSH=false
ENV="development"
ONLY=""
VALID_ONLY_VALUES=(backend frontend file-service api-gateway notification-service call-service)

# ─── CLI flags ───────────────────────────────────────────────────────────────
for arg in "$@"; do
  case $arg in
    --push)        PUSH=true ;;
    --env=*)       ENV="${arg#*=}" ;;
    --only=*)      ONLY="${arg#*=}" ;;
    -h|--help)
      echo "Usage: ./deploy-prod.sh [--push] [--env=development|staging|production] [--only=<service>]"
      echo "  --only=<service>  Rebuild and restart a single app container instead of the whole stack."
      echo "                    <service> is one of: ${VALID_ONLY_VALUES[*]}"
      echo "                    Skips infra (Postgres/Keycloak/RabbitMQ/observability) restart;"
      echo "                    assumes the rest of the stack is already running."
      exit 0
      ;;
    *)
      echo "[ERROR] Unknown argument: $arg"
      echo "Usage: ./deploy-prod.sh [--push] [--env=development|staging|production] [--only=<service>]"
      exit 1
      ;;
  esac
done

if [[ -n "$ONLY" ]]; then
  _only_valid=false
  for _v in "${VALID_ONLY_VALUES[@]}"; do [[ "$ONLY" == "$_v" ]] && _only_valid=true; done
  if ! $_only_valid; then
    echo "[ERROR] Unknown --only value '$ONLY'. Use one of: ${VALID_ONLY_VALUES[*]}"
    exit 1
  fi
fi

# Returns true if the given service should be built/(re)started this run —
# i.e. no --only was given (full deploy) or it matches the requested one.
service_selected() { [[ -z "$ONLY" || "$ONLY" == "$1" ]]; }

# ─── Helpers ─────────────────────────────────────────────────────────────────
log()  { echo "[$(date '+%H:%M:%S')] $*"; }
ok()   { echo "[$(date '+%H:%M:%S')] ✓ $*"; }
err()  { echo "[$(date '+%H:%M:%S')] ✗ $*" >&2; exit 1; }

ensure_keycloak_db() {
  local pg_user="${POSTGRES_USER:-admin}"
  log "Waiting for PostgreSQL to be ready..."
  local i=0
  until docker exec wacchat-db pg_isready -U "$pg_user" >/dev/null 2>&1; do
    (( ++i )); if (( i >= 30 )); then err "PostgreSQL did not become ready in time"; fi
    sleep 2
  done
  if docker exec wacchat-db psql -U "$pg_user" -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname = 'keycloak'" | grep -q 1; then
    ok "keycloak database already exists"
  else
    log "Creating keycloak database (first run against this volume)..."
    docker exec wacchat-db psql -U "$pg_user" -d postgres -c "CREATE DATABASE keycloak"
    ok "keycloak database created"
  fi
}

set_keycloak_admin_email() {
  [[ -z "${ADMIN_EMAIL:-}"              ]] && return 0
  [[ -z "${KEYCLOAK_ADMIN_USERNAME:-}"  ]] && return 0
  [[ -z "${KEYCLOAK_ADMIN_PASSWORD:-}"  ]] && return 0
  local kc="http://localhost:8180"
  log "Waiting for Keycloak to be ready..."
  local i=0
  until curl -sf "$kc/realms/master" >/dev/null 2>&1; do
    (( ++i )); if (( i >= 30 )); then log "Keycloak not ready — skipping admin email setup"; return 0; fi
    sleep 2
  done
  local token
  token=$(curl -sf -X POST "$kc/realms/master/protocol/openid-connect/token" \
    --data-urlencode "client_id=admin-cli" \
    --data-urlencode "username=${KEYCLOAK_ADMIN_USERNAME}" \
    --data-urlencode "password=${KEYCLOAK_ADMIN_PASSWORD}" \
    --data-urlencode "grant_type=password" 2>/dev/null \
    | grep -o '"access_token":"[^"]*"' | cut -d'"' -f4) || true
  [[ -z "$token" ]] && { log "Could not get Keycloak token — skipping admin email setup"; return 0; }
  local user_id
  user_id=$(curl -sf "$kc/admin/realms/master/users?username=${KEYCLOAK_ADMIN_USERNAME}" \
    -H "Authorization: Bearer $token" 2>/dev/null \
    | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4) || true
  [[ -z "$user_id" ]] && { log "Admin user not found in Keycloak — skipping email setup"; return 0; }
  curl -sf -X PUT "$kc/admin/realms/master/users/$user_id" \
    -H "Authorization: Bearer $token" \
    -H "Content-Type: application/json" \
    -d "{\"email\":\"${ADMIN_EMAIL}\",\"emailVerified\":true}" >/dev/null 2>&1 || true
  ok "Keycloak admin email set to ${ADMIN_EMAIL}"
}

ensure_admin_user() {
  [[ -z "${ADMIN_USER_PASSWORD:-}"      ]] && return 0
  [[ -z "${ADMIN_EMAIL:-}"              ]] && { log "ADMIN_EMAIL not set — skipping admin user seed"; return 0; }
  [[ -z "${KEYCLOAK_ADMIN_USERNAME:-}"  ]] && return 0
  [[ -z "${KEYCLOAK_ADMIN_PASSWORD:-}"  ]] && return 0
  local kc="http://localhost:8180"
  log "Waiting for Keycloak (wacchat realm) to be ready..."
  local i=0
  until curl -sf "$kc/realms/wacchat" >/dev/null 2>&1; do
    (( ++i )); if (( i >= 30 )); then log "wacchat realm not ready — skipping admin user seed"; return 0; fi
    sleep 2
  done
  local token
  token=$(curl -sf -X POST "$kc/realms/master/protocol/openid-connect/token" \
    --data-urlencode "client_id=admin-cli" \
    --data-urlencode "username=${KEYCLOAK_ADMIN_USERNAME}" \
    --data-urlencode "password=${KEYCLOAK_ADMIN_PASSWORD}" \
    --data-urlencode "grant_type=password" 2>/dev/null \
    | grep -o '"access_token":"[^"]*"' | cut -d'"' -f4) || true
  [[ -z "$token" ]] && { log "Could not get Keycloak token — skipping admin user seed"; return 0; }

  local user_id
  user_id=$(curl -sf "$kc/admin/realms/wacchat/users?email=${ADMIN_EMAIL}&exact=true" \
    -H "Authorization: Bearer $token" 2>/dev/null \
    | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4) || true

  if [[ -z "$user_id" ]]; then
    log "Creating admin user (${ADMIN_EMAIL}) in wacchat realm..."
    curl -sf -X POST "$kc/admin/realms/wacchat/users" \
      -H "Authorization: Bearer $token" \
      -H "Content-Type: application/json" \
      -d "{\"username\":\"${ADMIN_EMAIL}\",\"email\":\"${ADMIN_EMAIL}\",\"firstName\":\"Giuseppe Pio\",\"lastName\":\"Ruocco\",\"enabled\":true,\"emailVerified\":true,\"credentials\":[{\"type\":\"password\",\"value\":\"${ADMIN_USER_PASSWORD}\",\"temporary\":false}]}" \
      >/dev/null 2>&1 || { log "Failed to create admin user — skipping"; return 0; }
    user_id=$(curl -sf "$kc/admin/realms/wacchat/users?email=${ADMIN_EMAIL}&exact=true" \
      -H "Authorization: Bearer $token" 2>/dev/null \
      | grep -o '"id":"[^"]*"' | head -1 | cut -d'"' -f4) || true
    [[ -z "$user_id" ]] && { log "Admin user created but could not read back id — skipping .env update"; return 0; }
    ok "Admin user (${ADMIN_EMAIL}) created in wacchat realm"
  else
    ok "Admin user (${ADMIN_EMAIL}) already exists in wacchat realm"
  fi

  if [[ -z "${ADMIN_USER_ID:-}" ]]; then
    if grep -q '^ADMIN_USER_ID=' "$SCRIPT_DIR/.env"; then
      sed -i.bak "s/^ADMIN_USER_ID=.*/ADMIN_USER_ID=${user_id}/" "$SCRIPT_DIR/.env" && rm -f "$SCRIPT_DIR/.env.bak"
    else
      echo "ADMIN_USER_ID=${user_id}" >> "$SCRIPT_DIR/.env"
    fi
    ADMIN_USER_ID="$user_id"
    ok "Wrote ADMIN_USER_ID=${user_id} to .env"
  fi
}

# ─── Preflight checks ────────────────────────────────────────────────────────
log "=== WacChat deploy — env=$ENV ==="

[[ -f "$SCRIPT_DIR/docker-compose.yml" ]] || err "Must be run from the repo root (docker-compose.yml not found at $SCRIPT_DIR)"

command -v docker  >/dev/null 2>&1 || err "Docker is not installed or not in PATH"
docker info        >/dev/null 2>&1 || err "Docker daemon is not running"
command -v docker compose >/dev/null 2>&1 || \
  command -v docker-compose >/dev/null 2>&1 || \
  err "docker compose (v2) or docker-compose (v1) is required"

[[ -d "$BACKEND_DIR" ]]                 || err "Backend directory not found: $BACKEND_DIR"
[[ -d "$FRONTEND_DIR" ]]                || err "Frontend directory not found: $FRONTEND_DIR"
[[ -d "$FILE_SERVICE_DIR" ]]            || err "File-service directory not found: $FILE_SERVICE_DIR"
[[ -d "$API_GATEWAY_DIR" ]]             || err "API gateway directory not found: $API_GATEWAY_DIR"
[[ -d "$NOTIFICATION_SERVICE_DIR" ]]    || err "Notification-service directory not found: $NOTIFICATION_SERVICE_DIR"
[[ -d "$CALL_SERVICE_DIR" ]]            || err "Call-service directory not found: $CALL_SERVICE_DIR"

ok "Preflight checks passed"

# ─── Environment-specific overrides ──────────────────────────────────────────
case "$ENV" in
  production)
    TAG="stable"
    log "Production mode: tag=$TAG, push enforced"
    PUSH=true
    ;;
  staging)
    TAG="staging"
    log "Staging mode: tag=$TAG"
    ;;
  development)
    log "Development mode: tag=$TAG"
    ;;
  *)
    err "Unknown --env value '$ENV'. Use: development, staging, production"
    ;;
esac

# Compose the full image names (with optional registry prefix)
if [[ -n "$REGISTRY" ]]; then
  FULL_BACKEND="$REGISTRY/$IMAGE_BACKEND:$TAG"
  FULL_FRONTEND="$REGISTRY/$IMAGE_FRONTEND:$TAG"
  FULL_FILE_SERVICE="$REGISTRY/$IMAGE_FILE_SERVICE:$TAG"
  FULL_API_GATEWAY="$REGISTRY/$IMAGE_API_GATEWAY:$TAG"
  FULL_NOTIFICATION_SERVICE="$REGISTRY/$IMAGE_NOTIFICATION_SERVICE:$TAG"
  FULL_CALL_SERVICE="$REGISTRY/$IMAGE_CALL_SERVICE:$TAG"
else
  FULL_BACKEND="$IMAGE_BACKEND:$TAG"
  FULL_FRONTEND="$IMAGE_FRONTEND:$TAG"
  FULL_FILE_SERVICE="$IMAGE_FILE_SERVICE:$TAG"
  FULL_API_GATEWAY="$IMAGE_API_GATEWAY:$TAG"
  FULL_NOTIFICATION_SERVICE="$IMAGE_NOTIFICATION_SERVICE:$TAG"
  FULL_CALL_SERVICE="$IMAGE_CALL_SERVICE:$TAG"
fi

BUILD_FLAGS=""

if [[ -z "$ONLY" ]]; then
# ─── 1. Infrastructure (Postgres + Keycloak) ─────────────────────────────────
log "Stopping infrastructure containers for rebuild..."
COMPOSE_CMD="docker compose"
command -v docker compose >/dev/null 2>&1 || COMPOSE_CMD="docker-compose"

# Observability stack depends on the infra network, so stop it first
(cd "$SCRIPT_DIR/$COMPOSE_DIR" && $COMPOSE_CMD -f docker-compose.observability.yml down 2>/dev/null || true)

(cd "$SCRIPT_DIR/$COMPOSE_DIR" && $COMPOSE_CMD down)
ok "Infrastructure stopped"

# Release any containers or processes still holding the required ports
for port in 5433 8180; do
  # Stop Docker containers holding the port
  conflicting=$(docker ps --format '{{.ID}} {{.Ports}}' | grep ":${port}->" | awk '{print $1}' || true)
  if [[ -n "$conflicting" ]]; then
    log "Port $port held by Docker container $conflicting — stopping it..."
    docker stop "$conflicting"
  fi
  # Detect non-Docker processes holding the port and fail clearly
  pid=""
  if command -v fuser >/dev/null 2>&1; then
    pid=$(fuser "${port}/tcp" 2>/dev/null | tr -d ' ' || true)
  elif command -v ss >/dev/null 2>&1; then
    pid=$(ss -tlnp "sport = :${port}" 2>/dev/null | grep -oP 'pid=\K[0-9]+' | head -1 || true)
  fi
  if [[ -n "$pid" ]]; then
    proc=$(ps -p "$pid" -o comm= 2>/dev/null || echo "unknown")
    err "Port $port is held by system process '$proc' (PID $pid). Free it first and re-run deploy.sh."
  fi
done

# Force-remove named infra containers so docker compose always recreates them
# with the correct port mappings from docker-compose.yml (avoids stale containers
# created outside compose that end up without port bindings)
for name in wacchat-db keycloak-wacchat wacchat-rabbitmq; do
  if docker ps -a --format '{{.Names}}' | grep -qx "$name"; then
    log "Removing stale container: $name"
    docker rm -f "$name" 2>/dev/null || true
  fi
done

log "Starting PostgreSQL..."
(cd "$SCRIPT_DIR/$COMPOSE_DIR" && $COMPOSE_CMD up -d postgres)
ensure_keycloak_db

log "Starting infrastructure (Keycloak + RabbitMQ)..."
(cd "$SCRIPT_DIR/$COMPOSE_DIR" && $COMPOSE_CMD up -d)
ok "Infrastructure is up"
set_keycloak_admin_email
ensure_admin_user

# Observability stack needs the network created by the infra compose file
log "Starting observability stack (Prometheus, Grafana, Loki, Tempo)..."
(cd "$SCRIPT_DIR/$COMPOSE_DIR" && $COMPOSE_CMD -f docker-compose.observability.yml up -d)
ok "Observability stack is up"
else
  log "--only=$ONLY: skipping infra restart (stack assumed already running)"
fi

# ─── 5. Build backend image ──────────────────────────────────────────────────
if service_selected backend; then
  log "Building backend image: $FULL_BACKEND ..."
  docker build $BUILD_FLAGS \
    -t "$FULL_BACKEND" \
    -f "$BACKEND_DIR/Dockerfile" \
    "$WAC_DIR"
  ok "Backend image built: $FULL_BACKEND"
fi

# ─── 5b. Build file-service image ────────────────────────────────────────────
if service_selected file-service; then
  log "Building file-service image: $FULL_FILE_SERVICE ..."
  docker build $BUILD_FLAGS \
    -t "$FULL_FILE_SERVICE" \
    -f "$FILE_SERVICE_DIR/Dockerfile" \
    "$WAC_DIR"
  ok "File-service image built: $FULL_FILE_SERVICE"
fi

# ─── 5c. Build api-gateway image ─────────────────────────────────────────────
if service_selected api-gateway; then
  log "Building api-gateway image: $FULL_API_GATEWAY ..."
  docker build $BUILD_FLAGS \
    -t "$FULL_API_GATEWAY" \
    -f "$API_GATEWAY_DIR/Dockerfile" \
    "$API_GATEWAY_DIR"
  ok "API gateway image built: $FULL_API_GATEWAY"
fi

# ─── 5d. Build notification-service image ────────────────────────────────────
if service_selected notification-service; then
  log "Building notification-service image: $FULL_NOTIFICATION_SERVICE ..."
  docker build $BUILD_FLAGS \
    -t "$FULL_NOTIFICATION_SERVICE" \
    -f "$NOTIFICATION_SERVICE_DIR/Dockerfile" \
    "$WAC_DIR"
  ok "Notification-service image built: $FULL_NOTIFICATION_SERVICE"
fi

# ─── 5e. Build call-service image ────────────────────────────────────────────
if service_selected call-service; then
  log "Building call-service image: $FULL_CALL_SERVICE ..."
  docker build $BUILD_FLAGS \
    -t "$FULL_CALL_SERVICE" \
    -f "$CALL_SERVICE_DIR/Dockerfile" \
    "$WAC_DIR"
  ok "Call-service image built: $FULL_CALL_SERVICE"
fi

# ─── 3. Build frontend image ─────────────────────────────────────────────────
if service_selected frontend; then
  log "Building frontend image: $FULL_FRONTEND ..."
  docker build $BUILD_FLAGS \
    --build-arg APP_VERSION="$(git -C "$SCRIPT_DIR" rev-parse --short HEAD 2>/dev/null || echo dev)" \
    --build-arg APP_BUILD_TIME="$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
    -t "$FULL_FRONTEND" \
    -f "$FRONTEND_DIR/Dockerfile" \
    "$FRONTEND_DIR"
  ok "Frontend image built: $FULL_FRONTEND"
fi

# ─── 4. Push to registry (optional) ─────────────────────────────────────────
if $PUSH; then
  [[ -n "$REGISTRY" ]] || err "--push requires REGISTRY to be set in deploy.sh"
  log "Pushing images to $REGISTRY ..."
  service_selected backend              && docker push "$FULL_BACKEND"
  service_selected frontend             && docker push "$FULL_FRONTEND"
  service_selected file-service         && docker push "$FULL_FILE_SERVICE"
  service_selected api-gateway          && docker push "$FULL_API_GATEWAY"
  service_selected notification-service && docker push "$FULL_NOTIFICATION_SERVICE"
  service_selected call-service         && docker push "$FULL_CALL_SERVICE"
  ok "Images pushed to registry"
fi

# ─── 5. Stop and remove existing app containers ──────────────────────────────
ONLY_CONTAINERS=()
service_selected backend              && ONLY_CONTAINERS+=("$CONTAINER_BACKEND")
service_selected frontend             && ONLY_CONTAINERS+=("$CONTAINER_FRONTEND")
service_selected file-service         && ONLY_CONTAINERS+=("$CONTAINER_FILE_SERVICE")
service_selected api-gateway          && ONLY_CONTAINERS+=("$CONTAINER_API_GATEWAY")
service_selected notification-service && ONLY_CONTAINERS+=("$CONTAINER_NOTIFICATION_SERVICE")
service_selected call-service         && ONLY_CONTAINERS+=("$CONTAINER_CALL_SERVICE")
for name in "${ONLY_CONTAINERS[@]}"; do
  if docker ps -a --format '{{.Names}}' | grep -qx "$name"; then
    log "Stopping and removing container: $name"
    docker stop "$name" 2>/dev/null || true
    docker rm   "$name" 2>/dev/null || true
  fi
done
ok "Old containers removed"

# ─── 6a. Run file-service container ──────────────────────────────────────────
if service_selected file-service; then
log "Starting file-service container on port $PORT_FILE_SERVICE ..."
docker run -d \
  --name "$CONTAINER_FILE_SERVICE" \
  --network "wacchat_wacchat" \
  -p "127.0.0.1:$PORT_FILE_SERVICE:8080" \
  -e R2_ACCOUNT_ID="${R2_ACCOUNT_ID:-}" \
  -e R2_ACCESS_KEY_ID="${R2_ACCESS_KEY_ID:-}" \
  -e R2_SECRET_ACCESS_KEY="${R2_SECRET_ACCESS_KEY:-}" \
  -e R2_BUCKET_NAME="${R2_BUCKET_NAME:-}" \
  -e R2_PUBLIC_BASE_URL="${R2_PUBLIC_BASE_URL:-}" \
  -e FILE_SERVICE_INTERNAL_API_KEY="${FILE_SERVICE_INTERNAL_API_KEY:-}" \
  -e KEYCLOAK_ISSUER_URI="https://auth.wacchat.win/realms/wacchat" \
  -e OTLP_TRACING_ENDPOINT="http://wacchat-tempo:4318/v1/traces" \
  -e LOKI_URL="http://wacchat-loki:3100/loki/api/v1/push" \
  -e TRACING_SAMPLING_PROBABILITY="${TRACING_SAMPLING_PROBABILITY:-1.0}" \
  --restart unless-stopped \
  "$FULL_FILE_SERVICE"
ok "File-service container started"
fi

# ─── 6b. Run backend container ───────────────────────────────────────────────
if service_selected backend; then
log "Starting backend container on port $PORT_BACKEND ..."
docker run -d \
  --name "$CONTAINER_BACKEND" \
  --network "wacchat_wacchat" \
  -p "127.0.0.1:$PORT_BACKEND:8080" \
  -e SPRING_DATASOURCE_URL="jdbc:postgresql://wacchat-db:5432/${POSTGRES_DB:-wacchat_db}" \
  -e SPRING_DATASOURCE_USERNAME="${POSTGRES_USER:-admin}" \
  -e SPRING_DATASOURCE_PASSWORD="${POSTGRES_PASSWORD:-admin}" \
  -e KEYCLOAK_ISSUER_URI="https://auth.wacchat.win/realms/wacchat" \
  -e KEYCLOAK_ADMIN_URL="http://keycloak-wacchat:8080" \
  -e KEYCLOAK_ADMIN_USERNAME="${KEYCLOAK_ADMIN_USERNAME:-admin}" \
  -e KEYCLOAK_ADMIN_PASSWORD="${KEYCLOAK_ADMIN_PASSWORD:-admin}" \
  -e ADMIN_EMAIL="${ADMIN_EMAIL:-}" \
  -e ADMIN_USER_ID="${ADMIN_USER_ID:-}" \
  -e MAIL_USERNAME="${MAIL_USERNAME:-}" \
  -e MAIL_PASSWORD="${MAIL_PASSWORD:-}" \
  -e MAIL_FROM="${MAIL_FROM:-}" \
  -e GEMINI_API_KEY="${GEMINI_API_KEY:-}" \
  -e GEMINI_MODEL="${GEMINI_MODEL:-gemini-2.5-flash}" \
  -e GEMINI_BASE_URL="${GEMINI_BASE_URL:-https://generativelanguage.googleapis.com}" \
  -e ARNO_AVATAR_URL="${ARNO_AVATAR_URL:-}" \
  -e FILE_SERVICE_BASE_URL="http://wacchat-file-service:$PORT_FILE_SERVICE" \
  -e FILE_SERVICE_INTERNAL_API_KEY="${FILE_SERVICE_INTERNAL_API_KEY:-}" \
  -e RABBITMQ_HOST="wacchat-rabbitmq" \
  -e RABBITMQ_BACKEND_USER="$RABBITMQ_BACKEND_USER" \
  -e RABBITMQ_BACKEND_PASSWORD="$RABBITMQ_BACKEND_PASSWORD" \
  -e BACKEND_INTERNAL_API_KEY="${BACKEND_INTERNAL_API_KEY:-}" \
  -e OTLP_TRACING_ENDPOINT="http://wacchat-tempo:4318/v1/traces" \
  -e LOKI_URL="http://wacchat-loki:3100/loki/api/v1/push" \
  -e TRACING_SAMPLING_PROBABILITY="${TRACING_SAMPLING_PROBABILITY:-1.0}" \
  -v "$SCRIPT_DIR/wac/backend/uploads:/app/uploads" \
  --restart unless-stopped \
  "$FULL_BACKEND"
ok "Backend container started"
fi

# ─── 6c. Run notification-service container ──────────────────────────────────
if service_selected notification-service; then
log "Starting notification-service container on port $PORT_NOTIFICATION_SERVICE ..."
docker run -d \
  --name "$CONTAINER_NOTIFICATION_SERVICE" \
  --network "wacchat_wacchat" \
  -p "127.0.0.1:$PORT_NOTIFICATION_SERVICE:8084" \
  -e KEYCLOAK_ISSUER_URI="https://auth.wacchat.win/realms/wacchat" \
  -e RABBITMQ_HOST="wacchat-rabbitmq" \
  -e RABBITMQ_NOTIFICATION_USER="$RABBITMQ_NOTIFICATION_USER" \
  -e RABBITMQ_NOTIFICATION_PASSWORD="$RABBITMQ_NOTIFICATION_PASSWORD" \
  -e BACKEND_BASE_URL="http://wacchat-backend:$PORT_BACKEND" \
  -e BACKEND_INTERNAL_API_KEY="${BACKEND_INTERNAL_API_KEY:-}" \
  -e OTLP_TRACING_ENDPOINT="http://wacchat-tempo:4318/v1/traces" \
  -e LOKI_URL="http://wacchat-loki:3100/loki/api/v1/push" \
  -e TRACING_SAMPLING_PROBABILITY="${TRACING_SAMPLING_PROBABILITY:-1.0}" \
  --restart unless-stopped \
  "$FULL_NOTIFICATION_SERVICE"
ok "Notification-service container started"
fi

# ─── 6d. Run call-service container ──────────────────────────────────────────
if service_selected call-service; then
log "Starting call-service container on port $PORT_CALL_SERVICE ..."
docker run -d \
  --name "$CONTAINER_CALL_SERVICE" \
  --network "wacchat_wacchat" \
  -p "127.0.0.1:$PORT_CALL_SERVICE:8085" \
  -e KEYCLOAK_ISSUER_URI="https://auth.wacchat.win/realms/wacchat" \
  -e RABBITMQ_HOST="wacchat-rabbitmq" \
  -e RABBITMQ_CALL_USER="$RABBITMQ_CALL_USER" \
  -e RABBITMQ_CALL_PASSWORD="$RABBITMQ_CALL_PASSWORD" \
  -e BACKEND_BASE_URL="http://wacchat-backend:$PORT_BACKEND" \
  -e BACKEND_INTERNAL_API_KEY="${BACKEND_INTERNAL_API_KEY:-}" \
  -e OTLP_TRACING_ENDPOINT="http://wacchat-tempo:4318/v1/traces" \
  -e LOKI_URL="http://wacchat-loki:3100/loki/api/v1/push" \
  -e TRACING_SAMPLING_PROBABILITY="${TRACING_SAMPLING_PROBABILITY:-1.0}" \
  --restart unless-stopped \
  "$FULL_CALL_SERVICE"
ok "Call-service container started"
fi

# ─── 6e. Run api-gateway container ───────────────────────────────────────────
if service_selected api-gateway; then
log "Starting api-gateway container on port $PORT_API_GATEWAY ..."
docker run -d \
  --name "$CONTAINER_API_GATEWAY" \
  --network "wacchat_wacchat" \
  -p "127.0.0.1:$PORT_API_GATEWAY:8081" \
  -e BACKEND_BASE_URL="http://wacchat-backend:$PORT_BACKEND" \
  -e FILE_SERVICE_BASE_URL="http://wacchat-file-service:$PORT_FILE_SERVICE" \
  -e NOTIFICATION_SERVICE_BASE_URL="http://wacchat-notification-service:$PORT_NOTIFICATION_SERVICE" \
  -e CALL_SERVICE_BASE_URL="http://wacchat-call-service:8085" \
  -e OTLP_TRACING_ENDPOINT="http://wacchat-tempo:4318/v1/traces" \
  -e LOKI_URL="http://wacchat-loki:3100/loki/api/v1/push" \
  -e TRACING_SAMPLING_PROBABILITY="${TRACING_SAMPLING_PROBABILITY:-1.0}" \
  --restart unless-stopped \
  "$FULL_API_GATEWAY"
ok "API gateway container started"
fi

# ─── 7. Run frontend container ───────────────────────────────────────────────
if service_selected frontend; then
log "Starting frontend container on port $PORT_FRONTEND ..."
docker run -d \
  --name "$CONTAINER_FRONTEND" \
  --network "wacchat_wacchat" \
  -p "127.0.0.1:$PORT_FRONTEND:80" \
  --restart unless-stopped \
  "$FULL_FRONTEND"
ok "Frontend container started"
fi

# ─── 8. Health check ─────────────────────────────────────────────────────────
MAX_RETRIES=30
RETRY_INTERVAL=3

if service_selected backend; then
log "Waiting for backend to be ready..."
HEALTH_URL="http://localhost:$PORT_BACKEND/actuator/health"

healthy=false
for i in $(seq 1 $MAX_RETRIES); do
  http_code=$(curl -s -o /dev/null -w "%{http_code}" "$HEALTH_URL" 2>/dev/null || echo "000")
  if [[ "$http_code" == "200" ]] || [[ "$http_code" == "302" ]] || [[ "$http_code" == "401" ]]; then
    healthy=true
    break
  fi
  echo "  Attempt $i/$MAX_RETRIES — HTTP $http_code (retrying in ${RETRY_INTERVAL}s...)"
  sleep $RETRY_INTERVAL
done

if $healthy; then
  ok "Backend is healthy at $HEALTH_URL"
else
  echo ""
  log "Health check timed out after $((MAX_RETRIES * RETRY_INTERVAL))s — check container logs:"
  echo "  docker logs $CONTAINER_BACKEND"
fi
fi

# ─── 8b. API gateway health check ────────────────────────────────────────────
if service_selected api-gateway; then
log "Waiting for API gateway to be ready..."
GATEWAY_HEALTH_URL="http://localhost:$PORT_API_GATEWAY/actuator/health"

gateway_healthy=false
for i in $(seq 1 $MAX_RETRIES); do
  http_code=$(curl -s -o /dev/null -w "%{http_code}" "$GATEWAY_HEALTH_URL" 2>/dev/null || echo "000")
  if [[ "$http_code" == "200" ]]; then
    gateway_healthy=true
    break
  fi
  echo "  Attempt $i/$MAX_RETRIES — HTTP $http_code (retrying in ${RETRY_INTERVAL}s...)"
  sleep $RETRY_INTERVAL
done

if $gateway_healthy; then
  ok "API gateway is healthy at $GATEWAY_HEALTH_URL"
else
  echo ""
  log "API gateway health check timed out after $((MAX_RETRIES * RETRY_INTERVAL))s — check container logs:"
  echo "  docker logs $CONTAINER_API_GATEWAY"
fi
fi

# ─── 8c. Notification-service health check ──────────────────────────────────
if service_selected notification-service; then
log "Waiting for notification-service to be ready..."
NOTIFICATION_HEALTH_URL="http://localhost:$PORT_NOTIFICATION_SERVICE/actuator/health"

notification_healthy=false
for i in $(seq 1 $MAX_RETRIES); do
  http_code=$(curl -s -o /dev/null -w "%{http_code}" "$NOTIFICATION_HEALTH_URL" 2>/dev/null || echo "000")
  if [[ "$http_code" == "200" ]]; then
    notification_healthy=true
    break
  fi
  echo "  Attempt $i/$MAX_RETRIES — HTTP $http_code (retrying in ${RETRY_INTERVAL}s...)"
  sleep $RETRY_INTERVAL
done

if $notification_healthy; then
  ok "Notification-service is healthy at $NOTIFICATION_HEALTH_URL"
else
  echo ""
  log "Notification-service health check timed out after $((MAX_RETRIES * RETRY_INTERVAL))s — check container logs:"
  echo "  docker logs $CONTAINER_NOTIFICATION_SERVICE"
fi
fi

# ─── 8d. Call-service health check ───────────────────────────────────────────
if service_selected call-service; then
log "Waiting for call-service to be ready..."
CALL_HEALTH_URL="http://localhost:$PORT_CALL_SERVICE/actuator/health"

call_healthy=false
for i in $(seq 1 $MAX_RETRIES); do
  http_code=$(curl -s -o /dev/null -w "%{http_code}" "$CALL_HEALTH_URL" 2>/dev/null || echo "000")
  if [[ "$http_code" == "200" ]]; then
    call_healthy=true
    break
  fi
  echo "  Attempt $i/$MAX_RETRIES — HTTP $http_code (retrying in ${RETRY_INTERVAL}s...)"
  sleep $RETRY_INTERVAL
done

if $call_healthy; then
  ok "Call-service is healthy at $CALL_HEALTH_URL"
else
  echo ""
  log "Call-service health check timed out after $((MAX_RETRIES * RETRY_INTERVAL))s — check container logs:"
  echo "  docker logs $CONTAINER_CALL_SERVICE"
fi
fi

# ─── Summary ─────────────────────────────────────────────────────────────────
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
if [[ -n "$ONLY" ]]; then
  echo " Deploy complete — env=$ENV, service=$ONLY only"
else
  echo " Deploy complete — env=$ENV"
fi
echo ""
service_selected api-gateway          && echo " API Gateway         : http://localhost:$PORT_API_GATEWAY"
service_selected backend              && echo " Backend             : http://localhost:$PORT_BACKEND"
service_selected frontend             && echo " Frontend            : http://localhost:$PORT_FRONTEND"
service_selected file-service         && echo " File-service        : http://localhost:$PORT_FILE_SERVICE"
service_selected notification-service && echo " Notification-service: http://localhost:$PORT_NOTIFICATION_SERVICE"
service_selected call-service         && echo " Call-service        : http://localhost:$PORT_CALL_SERVICE"
service_selected backend              && echo " Swagger             : http://localhost:$PORT_BACKEND/swagger-ui.html"
if [[ -z "$ONLY" ]]; then
  echo " Keycloak            : http://localhost:8180"
  echo " RabbitMQ management : http://localhost:15672"
  echo " Grafana             : http://localhost:3000"
  echo " Prometheus          : http://localhost:9091"
fi
echo ""
echo " Logs:"
service_selected api-gateway          && echo "   docker logs -f $CONTAINER_API_GATEWAY"
service_selected backend              && echo "   docker logs -f $CONTAINER_BACKEND"
service_selected frontend             && echo "   docker logs -f $CONTAINER_FRONTEND"
service_selected file-service         && echo "   docker logs -f $CONTAINER_FILE_SERVICE"
service_selected notification-service && echo "   docker logs -f $CONTAINER_NOTIFICATION_SERVICE"
service_selected call-service         && echo "   docker logs -f $CONTAINER_CALL_SERVICE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
